//
//  LegalView.swift
//  TravelScoreriOS
//
//  Created by Lama Yassine on 2/4/26.
//

import Foundation
import SwiftUI

struct LegalView: View {
    private let sections: [(title: String, body: String)] = [
        (
            title: "How the app works",
            body: "Travel Adventure Finder is a planning and inspiration app. It may store profile details you choose to provide, account information, country preferences, passport and language preferences, bucket-list and traveled countries, trip plans, friend connections, and feedback you send through the app so those features can work across sessions and devices."
        ),
        (
            title: "Travel information and advisories",
            body: "The app may show visa guidance, destination scoring, safety and seasonality signals, budgeting context, and other travel-related summaries. Those materials are for general planning help only and can change quickly. Always confirm passports, visas, entry rules, advisories, health requirements, transport, and local conditions with official or primary sources before you book or travel."
        ),
        (
            title: "Accounts, sharing, and third parties",
            body: "If you sign in with Apple, Google, email, or another supported method, parts of your account are handled through those providers and our backend services. If you use trips, friends, profile sharing, or feedback tools, the information you choose to submit may be stored and processed to support syncing, notifications, support follow-up, and product improvement."
        ),
        (
            title: "Feedback, responsibility, and limits",
            body: "Feedback you send may be reviewed to improve the app and respond to your questions. You are responsible for the content you submit and for how you use planning information generated by the app. Travel Adventure Finder is provided on an as-is basis without guarantees of uninterrupted service, complete accuracy, or fitness for a particular travel decision, and the app may change over time."
        )
    ]

    var body: some View {
        ZStack {
            Theme.pageBackground("travel2")
                .ignoresSafeArea()

            VStack(spacing: 0) {
                Theme.titleBanner(String(localized: "legal.title"))

                ScrollView {
                    VStack(spacing: 20) {
                        ForEach(Array(sections.enumerated()), id: \.offset) { _, section in
                            legalSection(
                                title: section.title,
                                body: section.body
                            )
                        }
                    }
                    .padding(.top, 12)
                    .padding(.bottom, 32)
                }
            }
        }
        .navigationTitle("")
        .navigationBarTitleDisplayMode(.inline)
    }

    private func legalSection(title: String, body: String) -> some View {
        Theme.scrapbookSection {
            Text(title)
                .font(.headline)
                .foregroundStyle(Theme.textPrimary)

            Text(body)
                .font(.subheadline)
                .foregroundStyle(Theme.textSecondary)
        }
    }
}
