-- Generated from researched place-language override batches:
--   place_language_overrides.researched.batch1.json
--   place_language_overrides.researched.batch2.json
--   place_language_overrides.researched.batch3.json

insert into place_language_profile_overrides (
  place_type,
  place_code,
  languages,
  notes,
  override_reason,
  evidence
)
values
  ('country', 'LB', '[{"code":"ar","type":"official","coverage":1},{"code":"apc","type":"widely_spoken","coverage":1},{"code":"fr","type":"widely_spoken","coverage":0.65},{"code":"en","type":"widely_spoken","coverage":0.5}]'::jsonb, 'Lebanese spoken Arabic should match Levantine Arabic for everyday travel comfort. English and French are also practically useful in Lebanon.', 'dialect_and_traveler_usability_override', '[{"kind":"linguistic_reference","title":"Glottolog reference linking Lebanese Arabic to North Levantine Spoken [apc]","url":"https://glottolog.org/resource/reference/id/661333","note":"Supports mapping Lebanese spoken Arabic to the app language code apc."},{"kind":"general_reference","title":"Britannica: Lebanon","url":"https://www.britannica.com/place/Lebanon","note":"Britannica describes Arabic as the official language and French and English as widely spoken."}]'::jsonb),
  ('country', 'AW', '[{"code":"pap","type":"official","coverage":1},{"code":"nl","type":"official","coverage":1},{"code":"en","type":"widely_spoken","coverage":0.9},{"code":"es","type":"widely_spoken","coverage":0.75}]'::jsonb, 'Aruba should score highly for English usability in traveler reality, not just official-language baseline.', 'tourism_language_override', '[{"kind":"official_tourism","title":"Aruba.com official travel guide","url":"https://www.aruba.com/us/blog/the-official-aruba-travel-guide","note":"Official tourism copy says most Arubans also speak English and Spanish and are happy to help guests in English."},{"kind":"official_tourism","title":"Aruba.com Papiamento page","url":"https://www.aruba.com/uk/our-island/history-and-culture/papiamento","note":"Official tourism page confirms Papiamento and Dutch as official languages."}]'::jsonb),
  ('country', 'AD', '[{"code":"ca","type":"official","coverage":1},{"code":"es","type":"widely_spoken","coverage":0.9},{"code":"fr","type":"widely_spoken","coverage":0.7},{"code":"pt","type":"minor","coverage":0.35},{"code":"en","type":"tourist","coverage":0.45}]'::jsonb, 'Andorra should not behave like a Catalan-only destination. Spanish and French are very present; English is useful in tourism but not as universal as Spanish or French.', 'multilingual_tourism_override', '[{"kind":"official_tourism","title":"Visit Andorra essential information","url":"https://visitandorra.com/en/essential-information-about-andorra/","note":"Official tourism site says Catalan is official and Spanish, French, and Portuguese are very present."},{"kind":"inference","title":"Visit Andorra English-language site","url":"https://visitandorra.com/en/","note":"English inclusion is a tourism-utility override rather than an official-language claim."}]'::jsonb),
  ('country', 'SY', '[{"code":"ar","type":"official","coverage":1},{"code":"apc","type":"widely_spoken","coverage":1},{"code":"en","type":"minor","coverage":0.2},{"code":"fr","type":"minor","coverage":0.15}]'::jsonb, 'Syria should recognize Levantine Arabic for everyday spoken compatibility. English and French remain secondary but present, especially in urban and educated contexts.', 'dialect_and_traveler_usability_override', '[{"kind":"linguistic_reference","title":"North Levantine Arabic [apc] primary country is Syria","url":"https://dbs.org/en/research/languages/apc/","note":"Digital Bible Society language profile states North Levantine Arabic [apc] has Syria as its primary country and is spoken across the Levant."},{"kind":"general_reference","title":"Britannica Students: Syria","url":"https://kids.britannica.com/students/article/Syria/277994","note":"Britannica says Arabic is the official and most widely spoken language and that English and French are also used, especially in urban areas and among the educated."}]'::jsonb),
  ('country', 'JO', '[{"code":"ar","type":"official","coverage":1},{"code":"apc","type":"widely_spoken","coverage":0.9},{"code":"en","type":"widely_spoken","coverage":0.55}]'::jsonb, 'Jordan should recognize Levantine Arabic for spoken compatibility, while English is broadly useful in cities and tourism.', 'dialect_and_traveler_usability_override', '[{"kind":"linguistic_reference","title":"North Levantine Arabic [apc] spoken in Jordan","url":"https://dbs.org/en/research/languages/apc/","note":"The language profile describes Levantine Arabic [apc] as spoken in Jordan as part of the Levant."},{"kind":"official_tourism","title":"Visit Jordan: Just the facts","url":"https://international.visitjordan.com/page/16/just-the-facts","note":"Jordan Tourism Board says Arabic is official and English is widely spoken, especially in cities."}]'::jsonb),
  ('country', 'PS', '[{"code":"ar","type":"official","coverage":1},{"code":"apc","type":"widely_spoken","coverage":1},{"code":"en","type":"tourist","coverage":0.4}]'::jsonb, 'Palestine should treat Levantine Arabic as the practical spoken match. English is useful in many tourism and education contexts but not universal.', 'dialect_and_traveler_usability_override', '[{"kind":"linguistic_reference","title":"North Levantine Arabic [apc] spoken in Palestine","url":"https://dbs.org/en/research/languages/apc/","note":"The language profile describes Levantine Arabic [apc] as spoken in Palestine."},{"kind":"official_tourism","title":"Travel Palestine tourism interpretation center","url":"https://www.travelpalestine.ps/en/Site/67/Tourism-Interpretation-Center","note":"Official tourism content notes documentary and visitor-facing services in Arabic and English."}]'::jsonb),
  ('country', 'IL', '[{"code":"he","type":"official","coverage":1},{"code":"ar","type":"minor","coverage":0.35},{"code":"apc","type":"minor","coverage":0.3},{"code":"en","type":"widely_spoken","coverage":0.85}]'::jsonb, 'Israel should score highly for English traveler usability. Hebrew dominates, while Arabic and Levantine Arabic remain important for Arab communities and some traveler interactions.', 'multilingual_traveler_usability_override', '[{"kind":"general_reference","title":"Britannica: Israel","url":"https://www.britannica.com/place/Israel","note":"Britannica describes Hebrew as official and Arabic as having special status."},{"kind":"general_reference","title":"Britannica Students: Israel","url":"https://kids.britannica.com/students/article/Israel/275101","note":"Britannica says Israeli Arabs speak a dialect of Levantine Arabic and that English is widely spoken."}]'::jsonb),
  ('country', 'AE', '[{"code":"ar","type":"official","coverage":1},{"code":"en","type":"widely_spoken","coverage":0.95}]'::jsonb, 'The UAE should score very highly for English traveler usability. Arabic remains official, but English is deeply embedded in everyday travel and business.', 'tourism_language_override', '[{"kind":"official_tourism","title":"Experience Abu Dhabi FAQs","url":"https://www.visitabudhabi.ae/en/faqs","note":"Official tourism site says English is widely spoken in Abu Dhabi and that most business transactions are conducted in English."},{"kind":"general_reference","title":"Britannica: United Arab Emirates languages and religion","url":"https://www.britannica.com/place/United-Arab-Emirates/Languages-and-religion","note":"Britannica says English is widely spoken in the UAE."}]'::jsonb),
  ('country', 'QA', '[{"code":"ar","type":"official","coverage":1},{"code":"en","type":"widely_spoken","coverage":0.85}]'::jsonb, 'Qatar should score highly for English traveler usability in public-facing contexts while Arabic remains official.', 'tourism_language_override', '[{"kind":"official_tourism","title":"Visit Qatar first-time visitor guide","url":"https://visitqatar.com/intl-en/plan-your-trip/guides/first-time-visitor-guide","note":"Official tourism guidance says Arabic is official and English is commonly spoken at public places."}]'::jsonb),
  ('country', 'BH', '[{"code":"ar","type":"official","coverage":1},{"code":"en","type":"widely_spoken","coverage":0.85}]'::jsonb, 'Bahrain should score highly for English traveler usability, especially in tourist and commercial settings.', 'tourism_language_override', '[{"kind":"official_tourism","title":"Bahrain Tourism FAQs","url":"https://www.bahrain.com/en/faqs","note":"Official tourism FAQs say English is widely spoken, especially in hotels, restaurants, shops, and tourist areas."},{"kind":"official_tourism","title":"About Bahrain","url":"https://www.bahrain.com/en/about-bahrain","note":"Official tourism site says Arabic is official and English is widely spoken, with bilingual signage."}]'::jsonb),
  ('country', 'KW', '[{"code":"ar","type":"official","coverage":1},{"code":"en","type":"widely_spoken","coverage":0.6}]'::jsonb, 'Kuwait should reflect strong Arabic baseline with meaningful English usability in everyday modern services and travel contexts.', 'traveler_usability_override', '[{"kind":"general_reference","title":"Britannica: Kuwait","url":"https://www.britannica.com/place/Kuwait/Climate","note":"Britannica says Kuwaitis speak Gulf Arabic and English is the second language taught in public schools."},{"kind":"government_reference","title":"Kuwait Government Online: Kuwait Finder app","url":"https://e.gov.kw/sites/kgoenglish/Pages/ApplicationPages/Application-KuwaitFinder.aspx","note":"Official app documentation highlights Arabic and English support for public navigation services."}]'::jsonb),
  ('country', 'EG', '[{"code":"ar","type":"official","coverage":1},{"code":"arz","type":"widely_spoken","coverage":1},{"code":"en","type":"widely_spoken","coverage":0.45},{"code":"fr","type":"minor","coverage":0.3}]'::jsonb, 'Egypt should match Egyptian Arabic in daily speech and give meaningful credit for English and some French among educated and tourism-facing contexts.', 'dialect_and_traveler_usability_override', '[{"kind":"general_reference","title":"Britannica: Languages of Egypt","url":"https://www.britannica.com/place/Egypt/Languages","note":"Britannica explains that Egyptians speak vernacular Egyptian Arabic and that most educated Egyptians are fluent in English or French or both."},{"kind":"government_reference","title":"Egypt Ministry of Tourism hotline service","url":"https://egymonuments.gov.eg/news/hot-line-service-19654/","note":"Official tourism hotline is available in Arabic and English for visitors."}]'::jsonb),
  ('country', 'MA', '[{"code":"ar","type":"official","coverage":1},{"code":"ary","type":"widely_spoken","coverage":1},{"code":"fr","type":"widely_spoken","coverage":0.8},{"code":"es","type":"minor","coverage":0.45},{"code":"en","type":"tourist","coverage":0.3}]'::jsonb, 'Morocco should match Moroccan Arabic and reflect the strong practical role of French and some Spanish, plus moderate English tourism usability.', 'dialect_and_traveler_usability_override', '[{"kind":"official_tourism","title":"Visit Morocco language guide","url":"https://www.visitmorocco.com/en/useful-information/language","note":"Official tourism guide says Morocco''s official languages are Arabic and Amazigh, virtually all Moroccans understand French, and Spanish is widespread in northern and southern Morocco."},{"kind":"general_reference","title":"Britannica: Tamazight language","url":"https://www.britannica.com/topic/Tamazight-language","note":"Britannica notes that French and English are also used in Morocco."}]'::jsonb),
  ('country', 'DZ', '[{"code":"ar","type":"official","coverage":1},{"code":"arq","type":"widely_spoken","coverage":1},{"code":"fr","type":"widely_spoken","coverage":0.7},{"code":"en","type":"minor","coverage":0.2}]'::jsonb, 'Algeria should reflect Algerian Arabic in daily speech and the continued practical importance of French, while English remains lower-coverage.', 'dialect_and_traveler_usability_override', '[{"kind":"general_reference","title":"Britannica: Languages of Algeria","url":"https://www.britannica.com/place/Algeria/Languages","note":"Britannica says most Algerians speak vernacular Arabic and that French has long functioned as a lingua franca."},{"kind":"general_reference","title":"Britannica summary: Algeria","url":"https://www.britannica.com/summary/Algeria","note":"Britannica summary lists Arabic, Tamazight, and French in common national use."}]'::jsonb),
  ('country', 'TN', '[{"code":"ar","type":"official","coverage":1},{"code":"aeb","type":"widely_spoken","coverage":1},{"code":"fr","type":"widely_spoken","coverage":0.75},{"code":"en","type":"minor","coverage":0.3}]'::jsonb, 'Tunisia should match Tunisian Arabic in speech and reflect the major role of French, with English useful but less universal.', 'dialect_and_traveler_usability_override', '[{"kind":"general_reference","title":"Britannica: Languages of Tunisia","url":"https://www.britannica.com/place/Tunisia/Languages","note":"Britannica says Arabic is official, Tunisian Arabic is the native dialect, French plays an important role, and English also serves as a lingua franca to a lesser extent."},{"kind":"general_reference","title":"Britannica Students: Tunisia","url":"https://kids.britannica.com/students/article/Tunisia/277453","note":"Britannica says French is widely used in commerce and government."}]'::jsonb),
  ('country', 'BM', '[{"code":"en","type":"official","coverage":1}]'::jsonb, 'Bermuda should score English as fully compatible because English is the official and practical public language for travel.', 'official_language_override', '[{"kind":"general_reference","title":"Britannica: Bermuda","url":"https://www.britannica.com/place/Bermuda","note":"Britannica lists English as Bermuda''s official language."},{"kind":"government_reference","title":"Government of Bermuda immigration English proficiency requirements","url":"https://www.gov.bm/articles/department-immigration-clarifies-english-language-proficiency-requirements","note":"Government policy uses English as the required public-language standard for immigration and work-permit purposes."}]'::jsonb),
  ('country', 'BQ', '[{"code":"nl","type":"official","coverage":1},{"code":"en","type":"widely_spoken","coverage":0.8},{"code":"pap","type":"widely_spoken","coverage":0.65},{"code":"es","type":"minor","coverage":0.35}]'::jsonb, 'Caribbean Netherlands is an app-level aggregate of Bonaire, Sint Eustatius, and Saba. Dutch is the official administrative language, English dominates on Saba and St Eustatius, and Papiamentu is central on Bonaire.', 'aggregate_territory_language_override', '[{"kind":"government_reference","title":"CBS: Main languages of the Caribbean Netherlands","url":"https://longreads.cbs.nl/the-caribbean-netherlands-in-numbers-2022/what-percentage-of-the-population-speaks-dutch/","note":"CBS shows English as the main language on Saba and St Eustatius, while Papiamentu is the main language on Bonaire."},{"kind":"government_reference","title":"Government.nl: Papiamento on Bonaire officially recognised","url":"https://www.government.nl/latest/news/2024/01/29/papiamento-on-bonaire-now-officially-recognised-under-the-european-charter-for-regional-and-minority-languages","note":"The Dutch government formally recognises Papiamento on Bonaire."},{"kind":"official_tourism","title":"InfoBonaire language guide","url":"https://infobonaire.com/about-bonaire/languages/","note":"Tourism guidance for Bonaire says Dutch is official, Papiamentu is the native majority language, and English is also widely spoken."}]'::jsonb),
  ('country', 'CW', '[{"code":"pap","type":"official","coverage":1},{"code":"nl","type":"official","coverage":1},{"code":"en","type":"official","coverage":1},{"code":"es","type":"widely_spoken","coverage":0.65}]'::jsonb, 'Curaçao is fully multilingual for travelers: Papiamentu, Dutch, and English are official, and Spanish is also commonly usable.', 'multilingual_official_language_override', '[{"kind":"official_tourism","title":"Curaçao official tourism: native and official languages","url":"https://www.curacao.com/en/questions/culture/what-is-the-native-language-spoken-in-curacao","note":"Official tourism content says Dutch, Papiamentu, and English are official languages in Curaçao."},{"kind":"official_tourism","title":"Curaçao official tourism: English is widely spoken","url":"https://www.curacao.com/en/questions/culture/do-people-speak-english-in-curacao","note":"Official tourism content says most Curaçaoans speak English, Dutch, Spanish, and Papiamentu."}]'::jsonb),
  ('country', 'SX', '[{"code":"en","type":"official","coverage":1},{"code":"nl","type":"official","coverage":1},{"code":"fr","type":"widely_spoken","coverage":0.55},{"code":"es","type":"widely_spoken","coverage":0.4}]'::jsonb, 'Sint Maarten should not score as Dutch-only. English is official and dominant in daily life, with French and Spanish often usable in tourism-heavy settings.', 'multilingual_tourism_override', '[{"kind":"official_tourism","title":"Visit St. Maarten traveler information","url":"https://www.visitstmaarten.com/traveler-information/","note":"Official tourism guidance says Dutch is used in government on the Dutch side, English is widely spoken everywhere, and Spanish, Creole, and Papiamento are also widely spoken."},{"kind":"government_reference","title":"Sint Maarten policy document language profile","url":"https://www.sintmaartengov.org/Documents/Policies/Spatial%20development%20Strategy%20%2B%20attachements%20-%20Policy%20department%202022%20-%20Final.pdf","note":"Government planning material lists English and Dutch as official and shows English as the dominant public language."}]'::jsonb),
  ('country', 'KY', '[{"code":"en","type":"official","coverage":1}]'::jsonb, 'The Cayman Islands should score English as fully compatible because English is the official public language for travelers.', 'official_language_override', '[{"kind":"official_tourism","title":"Cayman Islands official tourism FAQs","url":"https://meet.visitcaymanislands.com/en-us/services-support/faqs","note":"Official tourism FAQs state that English is the official language of the Cayman Islands."}]'::jsonb),
  ('country', 'GI', '[{"code":"en","type":"official","coverage":1},{"code":"es","type":"widely_spoken","coverage":0.75}]'::jsonb, 'Gibraltar should score English as fully compatible while also recognizing that Spanish is widely usable in everyday local conversation.', 'official_and_bilingual_usability_override', '[{"kind":"official_tourism","title":"Visit Gibraltar general information","url":"https://www.visitgibraltar.gi/general-info","note":"Official tourism guidance says English is the official language and Spanish is widely spoken."},{"kind":"general_reference","title":"Britannica: Gibraltar","url":"https://www.britannica.com/place/Gibraltar","note":"Britannica says most Gibraltarians are bilingual in English and Spanish."}]'::jsonb)
on conflict (place_type, place_code) do update
set
  languages = excluded.languages,
  notes = excluded.notes,
  override_reason = excluded.override_reason,
  evidence = excluded.evidence,
  updated_at = now();
